### PR TITLE
Add enderchest support

### PR DESCRIPTION
**Pull request by THEJean-Kevin**

### CODE REVIEW

**Comment by trentech** [comment]
?

**Comment by THEJean-Kevin** [comment]
I add enderchest support, but i don't understand how to share the modif of your code

**Comment by trentech** [comment]
I already added enderchest support..

**Comment by THEJean-Kevin** [comment]
So can you upload the jar, because 2 people ask me to modify your plugin for add enderchest support

**Comment by trentech** [comment]
http://trentech.org/jenkins/job/Project%20Inventories/

**Comment by trentech** [comment]
Dev builds for all my plugins are available at

trentech.org/jenkins

**Comment by THEJean-Kevin** [comment]
ok nice, so I wish you Good coding

**Pull request closed without merging**
